<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="uSync.BackOffice" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConditionalProperties\ConditionalProperties.csproj" />
  </ItemGroup>

</Project>
