// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteConfigurationData, DeleteConfigurationErrors, DeleteConfigurationResponses, GetAllConfigurationsData, GetAllConfigurationsErrors, GetAllConfigurationsResponses, GetConfigurationData, GetConfigurationErrors, GetConfigurationResponses, PingData, PingErrors, PingResponses, SaveConfigurationData, SaveConfigurationErrors, SaveConfigurationResponses, WhatsMyNameData, WhatsMyNameErrors, WhatsMyNameResponses, WhatsTheTimeMrWolfData, WhatsTheTimeMrWolfErrors, WhatsTheTimeMrWolfResponses, WhoAmIData, WhoAmIErrors, WhoAmIResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ConditionalPropertiesService {
    public static deleteConfiguration<ThrowOnError extends boolean = false>(options: Options<DeleteConfigurationData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteConfigurationResponses, DeleteConfigurationErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/{propertyTypeKey}',
            ...options
        });
    }
    
    public static getConfiguration<ThrowOnError extends boolean = false>(options: Options<GetConfigurationData, ThrowOnError>) {
        return (options.client ?? client).get<GetConfigurationResponses, GetConfigurationErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/{propertyTypeKey}',
            ...options
        });
    }
    
    public static saveConfiguration<ThrowOnError extends boolean = false>(options: Options<SaveConfigurationData, ThrowOnError>) {
        return (options.client ?? client).post<SaveConfigurationResponses, SaveConfigurationErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/{propertyTypeKey}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getAllConfigurations<ThrowOnError extends boolean = false>(options?: Options<GetAllConfigurationsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAllConfigurationsResponses, GetAllConfigurationsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/all',
            ...options
        });
    }
}

export class ConditionalfieldsService {
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponses, PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/ping',
            ...options
        });
    }
    
    public static whatsMyName<ThrowOnError extends boolean = false>(options?: Options<WhatsMyNameData, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsMyNameResponses, WhatsMyNameErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/whatsMyName',
            ...options
        });
    }
    
    public static whatsTheTimeMrWolf<ThrowOnError extends boolean = false>(options?: Options<WhatsTheTimeMrWolfData, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsTheTimeMrWolfResponses, WhatsTheTimeMrWolfErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/whatsTheTimeMrWolf',
            ...options
        });
    }
    
    public static whoAmI<ThrowOnError extends boolean = false>(options?: Options<WhoAmIData, ThrowOnError>) {
        return (options?.client ?? client).get<WhoAmIResponses, WhoAmIErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/management/api/v1/conditionalfields/whoAmI',
            ...options
        });
    }
}
