<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.3.10" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageVersion Include="Umbraco.Cms" Version="17.0.1" />
    <PackageVersion Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="17.0.1" />
    <PackageVersion Include="uSync" Version="17.0.0" />
    <PackageVersion Include="uSync.BackOffice" Version="17.0.1" />
  </ItemGroup>
</Project>
